spring.application.name=ecommerse
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=mostafa732
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=your-very-secret-key-that-should-be-long-and-random-ecommerce
jwt.expiration=3600000 # 1 hour in milliseconds (1 * 60 * 60 * 1000)
# For 24 hours: jwt.expiration=86400000